# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_ID', models.AutoField(primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=200, unique=True)),
                ('employee_firstName', models.CharField(max_length=200)),
                ('employee_lastName', models.CharField(max_length=200)),
                ('employee_email', models.EmailField(max_length=254, unique=True)),
                ('employee_phoneNumber', models.CharField(max_length=200, unique=True)),
                ('employee_totalHours', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
