# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20171030_2135'),
        ('profiles', '0002_auto_20171029_2329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
