# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_ID', models.AutoField(primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=200, unique=True)),
                ('employee_firstName', models.CharField(max_length=200)),
                ('employee_lastName', models.CharField(max_length=200)),
                ('employee_email', models.EmailField(max_length=254, unique=True)),
                ('employee_phoneNumber', models.CharField(max_length=200, unique=True)),
                ('employee_totalHours', models.IntegerField()),
            ],
        ),
    ]
