# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(choices=[('UC', 'Under Charge'), ('OC', 'Overcharged'), ('NC', 'Normal Charge')], default='UC', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_totalHours',
            field=models.IntegerField(default=0),
        ),
    ]
