# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_auto_20171029_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivrables',
            fields=[
                ('delivrable_ID', models.AutoField(primary_key=True, serialize=False)),
                ('delivrable_title', models.CharField(max_length=200)),
                ('delivrable_main_category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_ID', models.AutoField(primary_key=True, serialize=False)),
                ('project_code', models.CharField(max_length=200, unique=True)),
                ('project_title', models.CharField(max_length=200)),
                ('project_status', models.CharField(choices=[('GO', 'On going'), ('HO', 'Hold'), ('RI', 'At risk')], default='GO', max_length=2)),
                ('project_phase', models.CharField(choices=[('CS', 'Case Study'), ('CO', 'Conceptual'), ('BE', 'Basic Engineering'), ('DE', 'Detailed Engineering')], default='CS', max_length=1)),
                ('jesa_role', models.CharField(choices=[('EP', 'EPC'), ('PM', 'PMC'), ('EM', 'EPCM')], default='EP', max_length=1)),
                ('estimated_hours', models.IntegerField()),
                ('actual_hours', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Implication_Percentage', models.IntegerField()),
                ('actual_hours', models.IntegerField()),
                ('estimated_hours', models.IntegerField()),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Employee')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Project')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='resources',
            unique_together=set([('Employee', 'Project')]),
        ),
    ]
