# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivrables',
            fields=[
                ('delivrable_ID', models.AutoField(primary_key=True, serialize=False)),
                ('delivrable_title', models.CharField(max_length=200)),
                ('delivrable_main_category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Implication_Percentage', models.IntegerField()),
                ('actual_hours', models.IntegerField()),
                ('estimated_hours', models.IntegerField()),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Project')),
            ],
        ),
    ]
