# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20171029_2329'),
        ('dashboard', '0002_delivrables_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='Employee',
            field=models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='profiles.Employee'),
        ),
        migrations.AlterUniqueTogether(
            name='resources',
            unique_together=set([('Employee', 'Project')]),
        ),
    ]
