# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_project_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('GO', 'On going'), ('HO', 'Hold'), ('RI', 'At risk')], default='GO', max_length=2),
        ),
    ]
