# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20171029_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='Employee',
            field=models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='team.Employee'),
        ),
    ]
